### ISSUE TITLE
No longer working on iOS. Shows blank screen.

### ISSUE THREAD

**Issue by mrpatricko** [w4rum/squadlanes#32]
It's been awhile since I used squadlanes on iOS but I know it worked not too long ago.

**Comment by w4rum** [comment]
Have you tried clearing your cache?

**Comment by mrpatricko** [comment]
I went ahead and cleared my cache but no luck. Also tried on other iOS devices, including BrowserStack for testing, and still no luck. When opening DevTools in BrowserStack, the console logs this error: "RangeError: Maximum call stack size exceeded."

**Comment by w4rum** [comment]
This might have been caused by the old path traversal logic. I just pushed the completely reworked system. Please try again.

**Comment by mrpatricko** [comment]
Hi Tim, it's still showing a blank screen along with the same error ("RangeError: Maximum call stack size exceeded."). I believe this is related to the '[Edge White Screen](https://github.com/w4rum/squadlanes/issues/24#issue-1146304423)' issue as well. I wish I could be of more help. Thanks for all you do!

**Comment by grey275** [comment]
it's possible that this is a bundler issue. see https://github.com/parcel-bundler/parcel/issues/7180

**Comment by mrpatricko** [comment]
You fixed it! Works on iOS now.

**Comment by w4rum** [comment]
> You fixed it! Works on iOS now.

Strange. I didn't actually do anything that I think would have fixed this.
